Xynthesis.Web/Controllers/ReporteProgramadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Xynthesis.Modelo;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using CrystalDecisions.Web;
using PagedList.Mvc;
using PagedList;
using System.IO;
using Xynthesis.Utilidades;
using Xynthesis.AccesoDatos;
using Xynthesis.Utilidades.Mensajes;
using System.Net;
using System.Configuration;

namespace Xynthesis.Web.Controllers
{
    public class ReporteProgramadoController : Controller
    {
        Utilidades.Constantes cons = new Constantes();
        AccesoDatos.ADReporteProgramado repProg = new ADReporteProgramado();
        AccesoDatos.ADUsuarios usua = new ADUsuarios();
        Utilidades.LogXynthesis log = new LogXynthesis();
        Xynthesis.Utilidades.Mensaje msg = new Mensaje();
        xynthesisEntities xyt = new xynthesisEntities();



        public ActionResult ListaRepProgramado(int? page)
        {

            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }


            try
            {
                int pageSize = cons.MaxRegGrilla == null ? 8 : Convert.ToInt32(cons.MaxRegGrilla);
                int pageIndex = 1;
                pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
                return View("ListaRepProgramado", repProg.ObtenerListaRepProgramado().ToList().ToPagedList(pageIndex, pageSize));

            }
            catch (Exception ex)
            {

                log.EscribaLog("LISTA DE REPORTE PROGRAMADO", "Action:Index " + ex.Message, Session["Nom_DomainUser"].ToString());
                return RedirectToAction("Error", "Error");
            }
        }


        public ActionResult OrdenFiltro(string sortOrder, string searchString, int? page)
        {
            try
            {
                int pageSize = cons.MaxRegGrilla == null ? 8 : Convert.ToInt32(cons.MaxRegGrilla);
                int pageIndex = 1;
                pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
                var res = repProg.OrdenFiltro(sortOrder, searchString);

                var pagedList1 = res.ToPagedList(pageIndex, pageSize);
                return View("ListaRepProgramado", pagedList1);
            }
            catch (Exception ex)
            {
                log.EscribaLog("ORDEN FILTRO", "Action:OrdenFiltro " + ex.Message, Session["Nom_DomainUser"].ToString());
                return RedirectToAction("Error", "Error");
            }
        }


        
        public ActionResult RepProgramado()
        {
            ViewBag.Frecuencia = new SelectList(xyt.xy_frecuencia.ToList(), "FrecuenciaId", "NombreFrecuencia");

            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }

            ViewData["confProgr"] = xyt.xy_configuracionrptprogramado.ToList();

            var lista = xyt.xy_reportes.ToList();

            return View(lista);
        }

        [HttpPost]
        public ActionResult RepProgramado(string NombreConfiguracion,string iden, string formato, int IdFrecuencia, string horaEjec, string email, string copiaCorreo, string asunto, string txtMensaje)
        {
            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }



            bool exists = (from nomb in xyt.xy_configuracionrptprogramado
                           where nomb.Nombre == NombreConfiguracion
                           select nomb).Any();

            if (exists == true)
            {
                ViewBag.Message = MensajesXynthesis.existeRegi;
                Session["mensale"] = MensajesXynthesis.existeRegi;
                Session["codigo"] = "0";
                return RedirectToAction("ListaRepProgramado");
            }

            string valor = iden;
            Char separador = '|';
            String[] letras = iden.Split(separador);
            string caracte = email.Replace(",",";");
            

            string correo = caracte.ToLower();
            string copiaCor = copiaCorreo.ToLower();

            try
            {
                for(int i = 0; i<letras.Length; i++)
                {
                    if (! letras[i].Equals(""))
                        xyt.xyp_InsRepProg(Convert.ToInt32(letras[i]), NombreConfiguracion, Convert.ToDateTime(horaEjec), formato, correo, copiaCor, asunto, txtMensaje, "", IdFrecuencia);
                }
                ViewBag.Message = MensajesXynthesis.Nuevo;
                Session["mensale"] = MensajesXynthesis.Nuevo;
                Session["codigo"] = "1";
                return RedirectToAction("ListaRepProgramado");
            }
            catch (Exception error)
            {
                Session["mensale"] = MensajesXynthesis.NoProcesa;
                Session["codigo"] = "0";
                log.EscribaLog("reporte", "Action:Create " + error.Message, Session["Nom_DomainUser"].ToString());
                return RedirectToAction("Error", "Error");
            }   


        }



        public ActionResult EditarRepProg(int? id)
        {
            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }

            ViewData["confProgr"] = xyt.xy_reportes.ToList();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                xy_configuracionrptprogramado confrep = xyt.xy_configuracionrptprogramado.Find(id);

                ViewData["listaReportes"] = (from s in xyt.xy_configuracionreporte where s.CondiguracionId == confrep.ConfiguracionId select s).ToList();

                if (confrep == null)
                {
                    return HttpNotFound();
                }

                string fecha = Convert.ToString(confrep.HoraEjecucion.ToString("hh:mm"));

                return View(confrep);

            }
            catch (Exception ex)
            {
                log.EscribaLog("EDITAR USUARIO", "Action:EditarRepProg " + ex.Message, Session["Nom_DomainUser"].ToString());
                return RedirectToAction("Error", "Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarRepProg(xy_configuracionrptprogramado xy_subscriber, int ConfiguracionId, string Nombre, string iden, string horaRep, string FormatoArchivo, string EmailFrom, string Asunto, string txtMensaje)
        {
            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }

            string caracte = EmailFrom.Replace(",", ";");


            string correo = caracte.ToLower();
     


            try {
                xyt.xyp_UpdRepProgra(ConfiguracionId, iden);
                xy_configuracionrptprogramado confrep = xyt.xy_configuracionrptprogramado.Find(xy_subscriber.ConfiguracionId);                

                confrep.FormatoArchivo = FormatoArchivo;
                confrep.EmailFrom = correo;
                confrep.HoraEjecucion = Convert.ToDateTime(horaRep);
                confrep.Asunto = Asunto;
                confrep.Mensaje = txtMensaje;

                repProg.EditarRepProgram(confrep);
                ViewBag.Message = MensajesXynthesis.Actualiza;
                Session["mensale"] = MensajesXynthesis.Actualiza;
                Session["codigo"] = "1";
                return RedirectToAction("ListaRepProgramado");
               

            }
            catch (Exception ex)
            {
                ViewBag.Message = MensajesXynthesis.NoProcesa;
                Session["mensale"] = MensajesXynthesis.NoProcesa;
                Session["codigo"] = "0";
                log.EscribaLog("EDITAR USUARIO", "Action:EditarRepProg " + ex.Message, Session["Nom_DomainUser"].ToString());
                return RedirectToAction("Error", "Error");
            }

        }

        public ActionResult EliminarRegistro(long? id)
        {
            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }
            return PartialView("../PopupDel/EliminarRegistro");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EliminarRegistro(int id, int? page)
        {
            msg = new Mensaje();
            msg.codigo = -1;
            if (Session["Ide_Subscriber"] == null)
            {

                return RedirectToAction("Login", "Acceso");
            }
            

            try
            {
                ViewBag.Message = "";

                int verifica = xyt.xy_configuracionrptprogramado.Where(i => i.ConfiguracionId == id).Count();
                if (verifica > 0)
                {
                    repProg.EliminarRepProgram(id);
                    ViewBag.Message = MensajesXynthesis.Elimina;
                    Session["mensale"] = MensajesXynthesis.Elimina;
                    Session["codigo"] = "1";
                }
                else
                {
                    ViewBag.Message = MensajesXynthesis.NoProcesa;
                    Session["mensale"] = MensajesXynthesis.NoProcesa;
                    Session["codigo"] = "0";
                }

                if (ViewBag.Message != "")
                    return Json(new { success = true });
                else
                    return Json(new { success = true });

            }
            catch (Exception ex)
            {

Xynthesis.Web/Views/ReporteProgramado/EditarRepProg.cshtml
@model Xynthesis.Modelo.xy_configuracionrptprogramado
@using Xynthesis.Utilidades.Mensajes
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="~/Content/Xynthesis.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
<script src="~/Scripts/NotacionDecimal.js"></script>

@{
    ViewBag.Title = "EditarCobertura";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var mod = (List<Xynthesis.Modelo.xy_reportes>)ViewData["confProgr"];
    var listaReportes = (List<Xynthesis.Modelo.xy_configuracionreporte>)ViewData["listaReportes"];
}

<div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="text-center">
            <h2><strong>Editar reporte programado</strong></h2>
        </div>

        <input id="msgCoberErra" type="hidden" value="@MensajesXynthesis.CoberErra" />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <section style="height:800px; width:100%;">
                <div class="form-horizontal">


                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.ConfiguracionId, htmlAttributes: new { @class = "control-label col-md-2 hidden-xs hidden-sm hidden-md hidden-lg" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ConfiguracionId, new { htmlAttributes = new { @class = "form-control hidden-xs hidden-sm hidden-md hidden-lg" } })
                            @Html.ValidationMessageFor(model => model.ConfiguracionId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-4">NOMBRE</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <!--Inicio de edicion de lista de reportes-->
                    <div class="row">
                        <label class="control-label col-md-4">REPORTES</label>
                            <textarea name="iden" id="iden" title="" placeholder="" class="hidden"></textarea>
                        <div class="col-md-8">
                            <div class="well" style="max-height: 200px;overflow: auto; border-radius:5px;">
                                <ul id="sampleList" class="list-group checked-list-box">

                                    @foreach (var item in mod)
                                    {
                                        var exis = 0;
                                        var id = 0;
                                        var nom="";
                                        foreach (var rep in listaReportes)
                                        {

                                            if (rep.xy_reportes.ReporteId == item.ReporteId)
                                            {
                                                exis = 1;


                                            }
                                            else
                                            {

                                            }
                                            id = @item.ReporteId;
                                        }
                                        nom="span"+id.ToString();
                                        if (exis == 1)
                                        {
                                            <li id=@item.ReporteId name=item.ReporteId class="list-group-item active list-group-item-primary" style="cursor:pointer;">@item.Nombre</li>
                                        }
                                        else
                                        {
                                            <li id=@item.ReporteId name=item.ReporteId class="list-group-item"><span name=@nom class="state-icon glyphicon glyphicon-unchecked" on></span>@item.Nombre</li>
                                        }



                                    }
                                </ul>
                            </div>
                        </div>
                            

                            <div class="col-lg-1"></div>
                        </div>
                    <!--fin de edicion de lista de reportes-->



                    <div class="form-group">
                        <label class="control-label col-md-4">HORA DE EJECUCIÓN</label>
                        <div class="col-md-8">
                            @{
                                var hor = Convert.ToString(Model.HoraEjecucion.ToString("HH:mm"));

                            }
                            @Html.TextBox("horaRep", hor, new { @class = "form-control", @type = "time", })
                            @Html.ValidationMessageFor(model => model.HoraEjecucion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4" for="codigo">FORMATO</label>
                        <div class="col-md-8">
                            <label>PDF</label>
                            @Html.RadioButtonFor(model => model.FormatoArchivo, "pdf")
                            <label>EXCEL</label>
                            @Html.RadioButtonFor(model => model.FormatoArchivo, "xls")
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-4" for="codigo">EMAIL</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.EmailFrom, new { htmlAttributes = new { @class = "form-control", @id = "emailform", @maxlength = "500", @title = "CORREO ELECTRONICO" } })
                            @Html.ValidationMessageFor(model => model.EmailFrom, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group" id="lblAlerta2" style="display:none">
                        <label class="control-label col-md-4 col-lg-3"></label>
                        <div class="col-lg-9 col-md-8 col-lg-8 pull-right">
                            <label style="color:#E81F2E;">(*) El campo es requerido</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-4" for="codigo">ASUNTO</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Asunto, new { htmlAttributes = new { @class = "form-control", @id = "asunto", @maxlength = "150", @title = "ASUNTO" } })
                            @Html.ValidationMessageFor(model => model.Asunto, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-4" for="codigo">MENSAJE</label>
                        <div class="col-md-8">
                            @*@Html.EditorFor(model => model.Mensaje, new { htmlAttributes = new { @class = "form-control", @id = "mensajes" } })*@
                            @Html.TextArea("txtMensaje", Model.Mensaje, new { @class = "form-control", style = "width: 100%; max-width:77%;", @title = "ESCRIBA UN MENSAJE", @placeholder = "ESCRIBA EL MENSAJE", @maxlength = "700", @rows = "6", @id = "mensajes" })
                            @Html.ValidationMessageFor(model => model.Mensaje, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group" id="lblAlerta6" style="display:none">
                        <label class="control-label col-md-4 col-lg-3"></label>
                        <div class="col-lg-9 col-md-8 col-lg-8 pull-right">
                            <label style="color:#E81F2E;">(*) El campo es requerido</label>
                        </div>
                    </div>

                    <br />

                    <div class="form-group">
                        <label class="col-md-4"></label>
                        <div class="col-md-8">
                            @Html.ActionLink("Regresar", "ListaRepProgramado", "ReporteProgramado", new { @class = "btn btn-success" })
                            <input type="submit" value="Actualizar" id="submit" class="btn btn-success" onclick="validate()" />
                        </div>
                    </div>

                </div>

            </section>
        }
    </div>
    <div class="col-md-2"></div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")   
}


<script type="text/javascript">   
    var cad = [];


    $(document).ready(function () {
        $('span').remove();
    });

    

    $(function () {
        $('.list-group.checked-list-box .list-group-item').each(function () {
            var $widget = $(this),
                $checkbox = $('<input type="checkbox" class="hidden" />'),
                color = ($widget.data('color') ? $widget.data('color') : "primary"),
                style = ($widget.data('style') == "button" ? "btn-" : "list-group-item-"),
                settings = {
                    on: {
                        icon: 'glyphicon glyphicon-check'
                    },
                    off: {
                        icon: 'glyphicon glyphicon-unchecked'
                    }
                };

            $widget.css('cursor', 'pointer')
            $widget.append($checkbox);

            // Event Handlers
            $widget.on('click', function () {
                $checkbox.prop('checked', !$checkbox.is(':checked'));
                $checkbox.triggerHandler('change');
                updateDisplay();
            });
            $checkbox.on('change', function () {
                updateDisplay();
            });


            // Actions
            function updateDisplay() {
                var isChecked = $checkbox.is(':checked');

                // Set the button's state
                $widget.data('state', (isChecked) ? "on" : "off");

                // Set the button's icon
                $widget.find('.state-icon')
                    .removeClass()
                    .addClass('state-icon ' + settings[$widget.data('state')].icon);

                // Update the button's color
                if (isChecked) {
                    $widget.addClass(style + color);
                } else {
                    $widget.removeClass(style + color);
                }
            }

            // Initialization
            function init() {

                if ($widget.data('checked') == true) {
                    $checkbox.prop('checked', !$checkbox.is(':checked'));
                }

                updateDisplay();

                // Inject the icon if applicable
                if ($widget.find('.state-icon').length == 0) {
                    $widget.prepend('<span class="state-icon ' + settings[$widget.data('state')].icon + '"></span>');
                }
            }
            init();
        });

        $('#get-checked-data').on('click', function (event) {
            event.preventDefault();
            var checkedItems = {}, counter = 0;
            $("#check-list-box ").each(function (idx, li) {
                checkedItems[counter] = $(li).text();
                counter++;
            });
            $('#display-json').html(JSON.stringify(checkedItems, null, '\t'));
        });
    });

    $('#submit').click(function () {

        $('#sampleList  li').each(function () {
            if ($(this).attr('class') == "list-group-item list-group-item-primary" || $(this).attr('class') == "list-group-item active list-group-item-primary")
            {
                 cad = cad + $(this).attr('id') + '|';
            }
        });
        var idd = document.getElementById("iden").innerHTML = cad;
        //alert(idd);
        $.ajax({
            type: 'POST',
            url: ' /ReporteProgramado/EditarRepProg',
            success: function (data) {
            },
            error: function (e) {
            }
        });
    });

    document.getElementById("submit").onclick = function () {
        var corr = document.getElementById("emailform").value; 
        var men = document.getElementById("mensajes").value;


        if (corr == "") {
            document.getElementById("lblAlerta2").style.display = "block"
            return false;
        } else if (men == "") {
            document.getElementById("lblAlerta6").style.display = "block"
            return false;
        } else {
            document.getElementById("lblAlerta2").style.display = "none"
            document.getElementById("lblAlerta6").style.display = "none"
            return true;
        }

    }
</script>

Xynthesis.Web/Views/ReporteProgramado/EliminarRepProgr.cshtml
@model Xynthesis.Modelo.xy_configuracionrptprogramado

@{
    ViewBag.Title = "Eliminar Sucursal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="col-md-3"></div>
    <div class="col-md-8">
        <h2><strong>Eliminar el reporte programado</strong></h2>
        <div>

    
                <div class="form-group row">                    
                    <div class="col-md-10">
                        <input type="text" class="form-control hidden" value="@Model.ConfiguracionId" disabled="disabled" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="text-right">
                        <label class="control-label col-md-2">NOMBRE</label>
                    </div>
                    <div class="col-md-10">
                        <input type="text" class="form-control" value="@Model.Nombre" disabled="disabled" />
                    </div>
                </div>
                <div class="form-group row">
                <div class="text-right">
                    <label class="control-label col-md-2">HORA</label>
                </div>
                <div class="col-md-10">
                    @{
                        var hor = Convert.ToString(Model.HoraEjecucion.ToString("HH:mm"));

                    }
                    @Html.TextBox("hora", hor, new { @class = "form-control", @type = "time", disabled = "disabled" })

                    @*<input type="text" class="form-control" value="@Model.HoraEjecucion" disabled="disabled" />*@
                </div>
                </div>

                <div class="form-group row">
                <div class="text-right">
                    <label class="control-label col-md-2">FORMATO</label>
                </div>
                <div class="col-md-10">
                    <input type="text" class="form-control" value="@Model.FormatoArchivo" disabled="disabled" />
                </div>
                </div>

                <div class="form-group row">
                <div class="text-right">
                    <label class="control-label col-md-2">EMAIL</label>
                </div>
                <div class="col-md-10">
                    <input type="text" class="form-control" value="@Model.EmailFrom" disabled="disabled" />
                </div>
                </div>

                <div class="form-group row">
                <div class="text-right">
                    <label class="control-label col-md-2">ASUNTO</label>
                </div>
                <div class="col-md-10">
                    <input type="text" class="form-control" value="@Model.Asunto" disabled="disabled" />
                </div>
                </div>

                <div class="form-group row">
                <div class="text-right">
                    <label class="control-label col-md-2">MENSAJE</label>
                </div>
                <div class="col-md-10">
                    <textarea class="form-control" value="@Model.Mensaje" disabled="disabled">@Model.Mensaje</textarea>
                </div>
            </div>            
        </div>


        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-10 row">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Eliminar" class="btn btn-success" />
                        @Html.ActionLink("Regresar", "ListaRepProgramado", "ReporteProgramado", new { @class = "btn btn-success" })
                    </div>
                }
            </div>
        </div>



    </div>
    <div class="col-md-3"></div>
</div>

Xynthesis.Web/Views/ReporteProgramado/MostrarFrecuencia.cshtml
@model IEnumerable<Xynthesis.Modelo.xy_frecuencia>

<select class="form-control" id="IdFrecuencia" name="IdFrecuencia">
    @foreach (var item in Model)
    {
        <option value="@item.FrecuenciaId">@item.NombreFrecuencia</option>
    }
</select>